In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
# 파일 불러오기
subway = pd.read_csv('subway_merged.csv', encoding='utf-8-sig')

In [22]:
subway.head()

       사용일자      역명  승차총승객수
0  20240101     애오개    2130
1  20240101  정부과천청사    3320
2  20240101     인덕원    8264
3  20240101      평촌    4908
4  20240101      범계   10865

In [27]:
# 강남구
gangnam_gu = ["강남", "신논현", "역삼", "선릉", "삼성", "압구정", "압구정로데오", "청담", "학동", "논현", "봉은사", "양재"]
# 서초구
seocho_gu = ["교대", "고속터미널", "서초", "남부터미널", "방배", "내방", "사평", "신반포", "잠원", "양재시민의숲", "우면동"]
# 송파구
songpa_gu = ["잠실", "잠실나루", "종합운동장", "잠실새내", "석촌", "가락시장", "문정", "장지", "복정", "오금", "방이", "몽촌토성", "한성백제", "송파", "거여", "마천"]
# 영등포구
yeongdeungpo_gu = ["영등포", "당산", "여의도", "국회의사당", "신도림", "영등포구청", "영등포시장", "문래", "양평", "선유도", "대림", "신길"]
# 마포구
mapo_gu = ["홍대입구", "합정", "공덕", "상수", "이대", "신촌", "광흥창", "대흥", "애오개", "마포", "서강대", "디지털미디어시티", "월드컵경기장", "마포구청"]
# 종로구
jongno_gu = ["종각", "종로3가", "종로5가", "광화문", "경복궁", "안국", "동대문", "혜화", "시청", "독립문", "서대문"]
# 중구
jung_gu = ["명동", "을지로입구", "동대문역사문화공원", "충무로", "회현", "시청", "을지로3가", "을지로4가", "동대입구", "약수", "버티고개"]
# 동대문구
dongdaemun_gu = ["청량리", "회기", "신설동", "제기동", "용두", "장한평", "답십리", "전농동", "이문동"]
# 성동구
seongdong_gu = ["왕십리", "성수", "건대입구", "한양대", "뚝섬", "서울숲", "응봉", "마장", "용답", "군자", "금호", "옥수"]
# 광진구
gwangjin_gu = ["건대입구", "강변", "구의", "아차산", "광나루", "중곡", "어린이대공원"]
# 성북구
seongbuk_gu = ["성신여대입구", "한성대입구", "길음", "안암", "고려대", "정릉", "보문", "월곡", "상월곡", "돌곶이"]
# 노원구
nowon_gu = ["노원", "상계", "중계", "하계", "당고개", "창동", "수락산", "마들", "태릉입구", "공릉"]
# 은평구
eunpyeong_gu = ["연신내", "불광", "구파발", "응암", "새절", "증산", "역촌", "녹번", "독바위", "연신내"]
# 서대문구
seodaemun_gu = ["신촌", "이대", "독립문", "홍제", "무악재", "가좌", "명지대"]
# 동작구
dongjak_gu = ["노량진", "이수", "숭실대입구", "중앙대입구", "상도", "장승배기", "신대방삼거리", "보라매역"]
# 관악구
gwanak_gu = ["서울대입구", "봉천", "신림", "낙성대", "사당", "남현동"]
# 구로구
guro_gu = ["구로디지털단지", "대림", "구로", "개봉", "온수", "천왕", "고척", "오류동"]
# 금천구
geumcheon_gu = ["가산디지털단지", "독산", "금천구청", "시흥사거리"]
# 강서구
gangseo_gu = ["김포공항", "발산", "마곡", "화곡", "가양", "염창", "등촌", "우장산", "개화산", "방화"]
# 양천구
yangcheon_gu = ["목동", "오목교", "신정", "신정네거리", "양천구청"]
# 도봉구
dobong_gu = ["창동", "방학", "도봉산", "쌍문", "도봉", "수유"]
# 강북구
gangbuk_gu = ["수유", "미아", "미아사거리", "삼양", "솔샘", "가오리", "4.19민주묘지", "북한산우이"]
# 중랑구
jungnang_gu = ["상봉", "망우", "면목", "사가정", "용마산", "중화", "묵동", "신내", "먹골"]
# 강동구
gangdong_gu = ["천호", "길동", "굽은다리", "상일동", "고덕", "명일", "암사", "둔촌동", "강동", "올림픽공원", "길동생태공원"]
subway.loc[subway["역명"].isin(gangnam_gu), "자치구"] = "강남구"
subway.loc[subway["역명"].isin(seocho_gu), "자치구"] = "서초구"
subway.loc[subway["역명"].isin(songpa_gu), "자치구"] = "송파구"
subway.loc[subway["역명"].isin(yeongdeungpo_gu), "자치구"] = "영등포구"
subway.loc[subway["역명"].isin(mapo_gu), "자치구"] = "마포구"
subway.loc[subway["역명"].isin(jongno_gu), "자치구"] = "종로구"
subway.loc[subway["역명"].isin(jung_gu), "자치구"] = "중구"
subway.loc[subway["역명"].isin(dongdaemun_gu), "자치구"] = "동대문구"
subway.loc[subway["역명"].isin(seongdong_gu), "자치구"] = "성동구"
subway.loc[subway["역명"].isin(gwangjin_gu), "자치구"] = "광진구"
subway.loc[subway["역명"].isin(seongbuk_gu), "자치구"] = "성북구"
subway.loc[subway["역명"].isin(nowon_gu), "자치구"] = "노원구"
subway.loc[subway["역명"].isin(eunpyeong_gu), "자치구"] = "은평구"
subway.loc[subway["역명"].isin(seodaemun_gu), "자치구"] = "서대문구"
subway.loc[subway["역명"].isin(dongjak_gu), "자치구"] = "동작구"
subway.loc[subway["역명"].isin(gwanak_gu), "자치구"] = "관악구"
subway.loc[subway["역명"].isin(guro_gu), "자치구"] = "구로구"
subway.loc[subway["역명"].isin(geumcheon_gu), "자치구"] = "금천구"
subway.loc[subway["역명"].isin(gangseo_gu), "자치구"] = "강서구"
subway.loc[subway["역명"].isin(yangcheon_gu), "자치구"] = "양천구"
subway.loc[subway["역명"].isin(dobong_gu), "자치구"] = "도봉구"
subway.loc[subway["역명"].isin(gangbuk_gu), "자치구"] = "강북구"
subway.loc[subway["역명"].isin(jungnang_gu), "자치구"] = "중랑구"
subway.loc[subway["역명"].isin(gangdong_gu), "자치구"] = "강동구"

In [23]:
station_info = pd.read_csv('sub_station_name.CSV', encoding='cp949')

In [4]:
station_info.head()

   자치구                                            해당역(호선)  역개수
0  강남구  삼성(2), 선릉(2), 역삼(2), 강남(2), 압구정(3), 신사(3), 매봉(...   21
1  강동구  천호(5), 강동(5), 길동(5), 굽은다리(5), 명일(5), 고덕(5), 상일...   15
2  강북구                             수유(4), 미아(4), 미아사거리(4)    3
3  강서구  방화(5), 개화산(5), 김포공항(5), 송정(5), 마곡(5), 발산(5), 우...    9
4  관악구                     낙성대(2), 서울대입구(2), 봉천(2), 신림(2)    4

In [11]:
# 자치구 정보에서 각 역명을 개별 행으로 분리
station_info_expanded = station_info.copy()

In [12]:
# '해당역(호선)' 컬럼을 ','로 나눈 후 각 역에서 괄호 제거하고 strip
station_info_expanded = station_info_expanded.drop('역개수', axis=1)
station_info_expanded = station_info_expanded.assign(
    역명목록=station_info_expanded['해당역(호선)'].str.split(', ')
).explode('역명목록')

In [13]:
# 괄호 제거하고 역명만 추출
station_info_expanded['역명'] = station_info_expanded['역명목록'].str.extract(r'([가-힣0-9]+)\(')
station_info_expanded = station_info_expanded[['자치구', '역명']]

In [8]:
# 중복 제거
station_info_expanded = station_info_expanded.drop_duplicates()

In [14]:
# subway에 자치구 매핑
subway_with_gu = pd.merge(subway, station_info_expanded, how='left', on='역명')

In [35]:
subway.head()

        사용일자  승차총승객수  자치구
0   20240101    2130  마포구
5   20240101    2195  강남구
13  20240101    4907  성동구
14  20240101    6451  강남구
39  20240101    2859  강서구

In [33]:
# 자치구가 NaN인 행 제거
subway = subway.dropna(subset=['자치구'])

In [34]:
# 역명 컬럼 제거
subway = subway.drop(columns=['역명','구'])

In [37]:
subway.shape

(77587, 3)

In [38]:
subway.head()

        사용일자  승차총승객수  자치구
0   20240101    2130  마포구
5   20240101    2195  강남구
13  20240101    4907  성동구
14  20240101    6451  강남구
39  20240101    2859  강서구

In [39]:
subway = subway.groupby(['사용일자', '자치구'])['승차총승객수'].sum().reset_index()

In [41]:
subway.head()

       사용일자  자치구  승차총승객수
0  20240101  강남구   95566
1  20240101  강동구   33742
2  20240101  강북구   22887
3  20240101  강서구   78185
4  20240101  관악구   64662

In [43]:
subway.shape

(8784, 3)

In [42]:
subway.to_csv('subway_with_gu.csv', index=False)